import type { Rule } from '../types.ts';
import { commentText, countAll, countMatches, isCommentLine, sourceFiles, totalLines, verdict } from './helpers.ts';

export const commentDensity: Rule = {
  id: 'comments.density',
  name: '正在测量注释密度',
  run(snap) {
    const files = sourceFiles(snap);
    const lines = totalLines(files);
    if (lines < 50) return [];
    let comments = 0;
    for (const f of files) {
      for (const l of f.content.split('\n')) if (isCommentLine(l)) comments++;
    }
    const ratio = comments / lines;
    const evidence = `注释 ${comments} 行 / 代码 ${lines} 行（${(ratio * 100).toFixed(1)}%）`;
    if (ratio > 0.3) {
      return [
        verdict(
          'comments.density',
          evidence,
          '每一行都被认真解释了一遍,包括 `i++`。人类写注释通常是为了三个月后的自己,而三个月后的自己也不想看',
          +12,
        ),
      ];
    }
    if (ratio > 0.15) {
      return [verdict('comments.density', evidence, '注释密度偏高。礼貌本身不可疑,可疑的是每个函数都礼貌得一样', +5)];
    }
    if (ratio < 0.02) {
      return [
        verdict(
          'comments.density',
          evidence,
          '几乎没有注释:作者相信三个月后的自己能看懂。三个月后作者证明了自己不能',
          -6,
        ),
      ];
    }
    return [verdict('comments.density', evidence, '注释密度处于正常区间，无话可说', 0)];
  },
};

const HUMAN_PHRASES = [
  '先这样', '不知道为什么', '别动', '别改', '暂时', '临时', '妈的', '玄学', '祖传',
  'hack', 'HACK', 'magic', '魔法', 'wtf', 'WTF', 'do not touch', "don't ask", 'somehow',
  'no idea why', 'it works', '这里有坑', '慎改',
];

export const humanComments: Rule = {
  id: 'comments.human-phrases',
  name: '正在扫描人类活动痕迹',
  run(snap) {
    // ponytail: 只扫注释文本，否则会命中代码里的字符串字面量（含本规则自己的词表）
    const text = commentText(sourceFiles(snap));
    const hits: string[] = [];
    let total = 0;
    for (const p of HUMAN_PHRASES) {
      const n = countMatches(text, new RegExp(p.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'));
      if (n > 0) {
        total += n;
        hits.push(`"${p}"×${n}`);
      }
    }
    if (total === 0) return [];
    return [
      verdict(
        'comments.human-phrases',
        `注释中出现 ${hits.slice(0, 5).join('、')}`,
        '情绪、无力感与求生欲挤在同一行注释里。模型会在生成代码前把情绪排干净',
        -Math.min(16, 5 + total),
      ),
    ];
  },
};

const AI_PHRASES = [
  'Certainly', 'As an AI', "Here's", "I've updated", 'Let me', 'I hope this helps',
  'Note that this', 'This function will', 'Feel free to', '希望这对你有帮助', '当然可以',
  '以下是', '我已经为你', 'Generated by', 'AI-generated',
];

export const aiComments: Rule = {
  id: 'comments.ai-phrases',
  name: '正在检索模型口癖',
  run(snap) {
    // ponytail: 只扫注释文本，否则会命中代码里的字符串字面量（含本规则自己的词表）
    const text = commentText(sourceFiles(snap));
    const hits: string[] = [];
    let total = 0;
    for (const p of AI_PHRASES) {
      const n = countMatches(text, new RegExp(p.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'));
      if (n > 0) {
        total += n;
        hits.push(`"${p}"×${n}`);
      }
    }
    if (total === 0) return [];
    return [
      verdict(
        'comments.ai-phrases',
        `源码中残留 ${hits.slice(0, 5).join('、')}`,
        '代码里出现了对话礼节。本中心认为源文件不需要跟任何人打招呼',
        +Math.min(30, 12 + total * 3),
        { highlight: true },
      ),
    ];
  },
};

export const todoMarkers: Rule = {
  id: 'comments.todo',
  name: '正在清点 TODO 的年龄',
  run(snap) {
    const files = sourceFiles(snap);
    const n = countAll(files, /\b(TODO|FIXME|XXX|HACK)\b/g);
    if (n === 0) {
      return [
        verdict(
          'comments.todo',
          '未发现任何 TODO/FIXME',
          '零 TODO。要么全部做完了,要么从来没打算做——本中心根据经验排除前者',
          +6,
        ),
      ];
    }
    const oldest = snap.commits.length
      ? snap.commits[snap.commits.length - 1]!.date
      : null;
    let days = 0;
    if (oldest) {
      const first = Date.parse(oldest);
      const last = snap.commits[0] ? Date.parse(snap.commits[0].date) : first;
      days = Math.max(0, Math.round((last - first) / 86400000));
    }
    if (days < 1) {
      return [
        verdict(
          'comments.todo',
          `发现 ${n} 处 TODO/FIXME/XXX/HACK，仓库活跃跨度 ${days} 天`,
          'TODO 与代码同一天出生，还没来得及被任何人遗忘，不构成人类存在的证据',
          +Math.min(10, 3 + Math.floor(n / 4)),
        ),
      ];
    }
    return [
      verdict(
        'comments.todo',
        `发现 ${n} 处 TODO/FIXME/XXX/HACK，仓库活跃跨度 ${days} 天`,
        `TODO 已存在 ${days} 天：已确认存在人类开发者`,
        -Math.min(12, 3 + Math.floor(n / 4)),
      ),
    ];
  },
};

export const bilingualComments: Rule = {
  id: 'comments.bilingual',
  name: '正在分析注释的语言构成',
  run(snap) {
    const files = sourceFiles(snap);
    let mixed = 0;
    for (const f of files) {
      for (const l of f.content.split('\n')) {
        if (!isCommentLine(l)) continue;
        if (/[一-龥]/.test(l) && /[A-Za-z]{4,}/.test(l)) mixed++;
      }
    }
    if (mixed === 0) return [];
    return [
      verdict(
        'comments.bilingual',
        `发现 ${mixed} 行中英混杂注释`,
        // ponytail: 中文项目里模型同样中英混写，这条只当弱证据
        '中英混写读起来很自然，但如今模型也这么写，本中心仅作参考',
        -Math.min(5, 2 + Math.floor(mixed / 20)),
      ),
    ];
  },
};

export const commentRules: Rule[] = [
  commentDensity,
  humanComments,
  aiComments,
  todoMarkers,
  bilingualComments,
];
